description: Journal of my tinkering.
name: C0hen
encoding: utf-8
exclude:
  - LICENSE
markdown: kramdown
permalink: /:slug/
favorite_color: blue
#theme: jekyll-theme-minimal
highlighter: rouge
plugins:
  - jekyll-seo-tag
kramdown:
  # parse_block_html: true
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  line_width: 72
  # Programmer's world compliant config: 
  # disable changing quotes to literary.
  smart_quotes: ["apos", "apos", "quot", "quot"]
  # inline table nil
  coderay_line_numbers: nil
  coderay_tab_width: 4
  # :span :div nil
  coderay_wrap: nil
  # Github Flavored Markdown parser
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › 
  # http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # https://github.com/jneen/rouge/blob/master/README.md
    line_format: '%i' # a sprintf template for the line number itself
    table_class: 'rouge-table'
    gutter_class: 'rouge-gutter'
    code_class: 'rouge-code'
    # css_class is lecagy
    css_class: 'highlighter-rouge'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
